name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Markdown
        uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: "**/*.md"

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v5

      - name: Check file size
        run: |
          find . -type f -size +5M | while read file; do
            echo "::error file=$file::File size exceeds 5MB limit"
            exit 1
          done

  review:
    name: Review Checks
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check documentation structure
        run: |
          if [ ! -f "Writerside/learnjava.tree" ]; then
            echo "::error::Missing learnjava.tree file"
            exit 1
          fi

      - name: Validate XML files
        run: |
          find . -name "*.xml" -type f -exec xmllint --noout {} \;

      - name: Check broken links
        run: |
          # Adicione aqui a lógica para verificar links quebrados
          echo "Checking for broken links..."